import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Activity, AlertTriangle, BookOpen, Brain, FileText, LayoutDashboard, MessageSquare, Plus, Search, Settings, Trash2, Users, Wind } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { adminApi, apiError, type AdminConversation, type AdminMood, type AdminSettings, type AdminUser, type Analytics, type BreathingExercise, type CampusResource, type SessionUser, type WellnessTip } from '../../api'
import { adminRoute, adminViewFor, type AdminView } from '../../routes'
import { AppShell, PageHeader, type NavItem } from '../layout/AppShell'
import Button from '../ui/Button'
import { FormField } from '../ui/FormField'
import { Modal } from '../ui/Modal'
import { Badge, ErrorState, LoadingState } from '../ui/Status'
import { DataTable, type Column } from './DataTable'

type AdminData = { analytics: Analytics; conversations: AdminConversation[]; alerts: AdminConversation[]; resources: CampusResource[]; tips: WellnessTip[]; exercises: BreathingExercise[]; moods: AdminMood[]; users: AdminUser[]; settings: AdminSettings }
const emptyData: AdminData = { analytics: { registeredStudents: 0, messages: 0, moodCheckIns: 0, riskAlerts: 0, categories: {} }, conversations: [], alerts: [], resources: [], tips: [], exercises: [], moods: [], users: [], settings: { aiProvider: '', model: '', storage: '', campusOrigin: '' } }
const nav: NavItem<AdminView>[] = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'conversations', label: 'Conversations', icon: MessageSquare }, { id: 'alerts', label: 'Risk alerts', icon: AlertTriangle }, { id: 'resources', label: 'Resources', icon: BookOpen }, { id: 'tips', label: 'Wellness tips', icon: FileText }, { id: 'exercises', label: 'Breathing exercises', icon: Wind }, { id: 'moods', label: 'Mood data', icon: Activity }, { id: 'users', label: 'Users', icon: Users }, { id: 'settings', label: 'Settings', icon: Settings }
]

export function AdminApp({ user, onSignOut }: { user: SessionUser; onSignOut: () => void }) {
  const location = useLocation(); const navigate = useNavigate(); const active = adminViewFor(location.pathname)
  const [data, setData] = useState<AdminData>(emptyData); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [toast, setToast] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [analytics, conversations, alerts, resources, tips, exercises, moods, users, settings] = await Promise.all([adminApi.analytics(), adminApi.conversations(), adminApi.alerts(), adminApi.resources(), adminApi.tips(), adminApi.exercises(), adminApi.moods(), adminApi.users(), adminApi.settings()]); setData({ analytics, conversations, alerts, resources, tips, exercises, moods, users, settings }) } catch (failure) { setError(apiError(failure)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 3000); return () => window.clearTimeout(timer) }, [toast])
  const update = <K extends keyof AdminData>(key: K, value: AdminData[K], message: string) => { setData(current => ({ ...current, [key]: value })); setToast(message) }
  return <AppShell productName="Campus Care Admin" user={user} active={active} navigation={nav.map(item => item.id === 'alerts' ? { ...item, badge: data.alerts.length } : item)} onNavigate={view => navigate(adminRoute(view))} onSignOut={onSignOut} footerNote="Administrative access. Student conversations may contain sensitive information.">
    {toast && <div className="toast" role="status">{toast}</div>}
    {loading ? <LoadingState label="Loading admin workspace…"/> : error ? <ErrorState message="Admin data could not be loaded." onRetry={load}/> : <AdminViewContent active={active} data={data} update={update}/>} 
  </AppShell>
}

function AdminViewContent({ active, data, update }: { active: AdminView; data: AdminData; update: <K extends keyof AdminData>(key: K, value: AdminData[K], message: string) => void }) {
  if (active === 'overview') return <Overview data={data}/>
  if (active === 'conversations') return <ConversationTable rows={data.conversations}/>
  if (active === 'alerts') return <AlertsTable rows={data.alerts}/>
  if (active === 'resources') return <ResourceManager rows={data.resources} onChange={rows => update('resources', rows, 'Resource list updated.')}/>
  if (active === 'tips') return <TipManager rows={data.tips} onChange={rows => update('tips', rows, 'Wellness tips updated.')}/>
  if (active === 'exercises') return <ExerciseManager rows={data.exercises} onChange={rows => update('exercises', rows, 'Breathing exercises updated.')}/>
  if (active === 'moods') return <MoodTable rows={data.moods}/>
  if (active === 'users') return <UserTable rows={data.users}/>
  return <SettingsPage settings={data.settings}/>
}

function Overview({ data }: { data: AdminData }) {
  const intents = Object.entries(data.analytics.categories).sort((a, b) => b[1] - a[1])
  return <div className="page"><PageHeader title="Overview" description="Current activity from the Campus Care development store."/>
    <div className="metric-grid"><Metric label="Students" value={data.analytics.registeredStudents}/><Metric label="Messages" value={data.analytics.messages}/><Metric label="Mood check-ins" value={data.analytics.moodCheckIns}/><Metric label="Risk alerts" value={data.analytics.riskAlerts} tone={data.analytics.riskAlerts ? 'danger' : undefined}/></div>
    <div className="admin-grid"><section className="panel"><h2>Common conversation categories</h2>{intents.length ? <div className="intent-list">{intents.map(([name, count]) => <div key={name}><span>{name}</span><strong>{count}</strong></div>)}</div> : <p className="empty-copy">No conversation categories have been recorded.</p>}</section><section className="panel"><h2>Operational status</h2><dl className="settings-list"><div><dt>Assistant</dt><dd>{data.settings.aiProvider || 'Not configured'} · {data.settings.model || 'No model'}</dd></div><div><dt>Storage</dt><dd>{data.settings.storage}</dd></div><div><dt>Alerts requiring review</dt><dd>{data.alerts.length}</dd></div></dl></section></div>
  </div>
}
function Metric({ label, value, tone }: { label: string; value: number; tone?: 'danger' }) { return <article className={`metric ${tone ? `metric-${tone}` : ''}`}><span>{label}</span><strong>{value}</strong></article> }

function useSearch<T>(rows: T[], text: (row: T) => string) { const [query, setQuery] = useState(''); const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? rows.filter(row => text(row).toLowerCase().includes(q)) : rows }, [rows, query]); return { query, setQuery, filtered } }
function SearchBar({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="search-field"><Search size={17}/><span className="sr-only">{placeholder}</span><input value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder}/></label> }

function ConversationTable({ rows }: { rows: AdminConversation[] }) {
  const { query, setQuery, filtered } = useSearch(rows, row => `${row.studentName} ${row.studentEmail} ${row.message} ${row.category}`)
  const columns: Column<AdminConversation>[] = [{ key: 'student', label: 'Student', render: row => <><strong>{row.studentName}</strong><small>{row.studentEmail}</small></> }, { key: 'role', label: 'Type', render: row => <Badge>{row.role === 'USER' ? 'Student' : 'Campus Care'}</Badge> }, { key: 'message', label: 'Message', render: row => <span className="cell-message">{row.message}</span> }, { key: 'category', label: 'Category', render: row => row.category ?? '—' }, { key: 'time', label: 'Created', render: row => new Date(row.createdAt).toLocaleString() }]
  return <div className="page"><PageHeader title="Conversations" description="Messages are visible only to authorized administrators in this development system."/><div className="filter-bar"><SearchBar value={query} onChange={setQuery} placeholder="Search conversations"/></div><DataTable rows={filtered} columns={columns} rowKey={row => row.id}/></div>
}
function AlertsTable({ rows }: { rows: AdminConversation[] }) {
  const columns: Column<AdminConversation>[] = [{ key: 'student', label: 'Student', render: row => <><strong>{row.studentName}</strong><small>{row.studentEmail}</small></> }, { key: 'message', label: 'Message', render: row => <span className="cell-message">{row.message}</span> }, { key: 'category', label: 'Category', render: row => <Badge tone="danger">{row.category ?? 'urgent'}</Badge> }, { key: 'time', label: 'Created', render: row => new Date(row.createdAt).toLocaleString() }]
  return <div className="page"><PageHeader title="Risk alerts" description="Review messages that matched an urgent safety rule. A match is not a diagnosis."/><div className="admin-warning"><AlertTriangle size={20}/><p>Campus Care does not contact emergency services automatically. Follow your college’s approved escalation process.</p></div><DataTable rows={rows} columns={columns} rowKey={row => row.id} emptyTitle="No risk alerts" emptyDescription="No messages have matched an urgent safety rule."/></div>
}

function ResourceManager({ rows, onChange }: { rows: CampusResource[]; onChange: (rows: CampusResource[]) => void }) {
  const [editing, setEditing] = useState<CampusResource | 'new' | null>(null); const [deleting, setDeleting] = useState<CampusResource | null>(null); const { query, setQuery, filtered } = useSearch(rows, row => `${row.title} ${row.kind} ${row.contact}`)
  const columns: Column<CampusResource>[] = [{ key: 'title', label: 'Resource', render: row => <><strong>{row.title}</strong><small>{row.description}</small></> }, { key: 'category', label: 'Category', render: row => row.kind }, { key: 'status', label: 'Status', render: row => <Badge tone={row.verified ? 'success' : 'warning'}>{row.verified ? 'Verified' : 'Unverified'}</Badge> }, { key: 'contact', label: 'Contact', render: row => row.contact }, { key: 'actions', label: 'Actions', render: row => <div className="row-actions"><Button size="small" variant="secondary" onClick={() => setEditing(row)}>Edit</Button><Button size="small" variant="ghost" onClick={() => setDeleting(row)} aria-label={`Delete ${row.title}`}><Trash2 size={16}/></Button></div> }]
  const remove = async () => { if (!deleting) return; await adminApi.deleteResource(deleting.id); onChange(rows.filter(item => item.id !== deleting.id)); setDeleting(null) }
  return <div className="page"><PageHeader title="Resources" description="Maintain campus contacts and the verification status shown to students." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add resource</Button>}/><div className="filter-bar"><SearchBar value={query} onChange={setQuery} placeholder="Search resources"/></div><DataTable rows={filtered} columns={columns} rowKey={row => row.id}/>{editing && <ResourceForm item={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSave={item => { onChange(editing === 'new' ? [...rows, item] : rows.map(row => row.id === item.id ? item : row)); setEditing(null) }}/>} {deleting && <ConfirmDelete name={deleting.title} onClose={() => setDeleting(null)} onConfirm={remove}/>}</div>
}

function ResourceForm({ item, onClose, onSave }: { item?: CampusResource; onClose: () => void; onSave: (item: CampusResource) => void }) {
  const [form, setForm] = useState({ title: item?.title ?? '', description: item?.description ?? '', contact: item?.contact ?? '', hours: item?.hours ?? '', kind: item?.kind ?? 'counselling', verified: item?.verified ?? false }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onSave(item ? await adminApi.updateResource(item.id, form) : await adminApi.addResource(form)) } catch (failure) { setError(apiError(failure)) } finally { setBusy(false) } }
  return <Modal title={item ? 'Edit resource' : 'Add resource'} description="Use contact details approved by the college." onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="inline-alert" role="alert">{error}</div>}<FormField label="Title" htmlFor="resource-title" required><input id="resource-title" required minLength={2} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/></FormField><FormField label="Description" htmlFor="resource-description" required><textarea id="resource-description" required minLength={5} rows={4} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/></FormField><div className="form-grid"><FormField label="Category" htmlFor="resource-category" required><input id="resource-category" required value={form.kind} onChange={event => setForm({ ...form, kind: event.target.value })}/></FormField><FormField label="Hours" htmlFor="resource-hours" required><input id="resource-hours" required value={form.hours} onChange={event => setForm({ ...form, hours: event.target.value })}/></FormField></div><FormField label="Contact" htmlFor="resource-contact" required><input id="resource-contact" required value={form.contact} onChange={event => setForm({ ...form, contact: event.target.value })}/></FormField><label className="checkbox-field"><input type="checkbox" checked={form.verified} onChange={event => setForm({ ...form, verified: event.target.checked })}/><span><strong>Verified by the college</strong><small>Only enable this after the contact and hours have been checked.</small></span></label><div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save resource'}</Button></div></form></Modal>
}

function TipManager({ rows, onChange }: { rows: WellnessTip[]; onChange: (rows: WellnessTip[]) => void }) {
  const [editing, setEditing] = useState<WellnessTip | 'new' | null>(null); const [deleting, setDeleting] = useState<WellnessTip | null>(null); const { query, setQuery, filtered } = useSearch(rows, row => `${row.title} ${row.category} ${row.body}`)
  const columns: Column<WellnessTip>[] = [{ key: 'title', label: 'Tip', render: row => <><strong>{row.title}</strong><small>{row.body}</small></> }, { key: 'category', label: 'Category', render: row => <Badge>{row.category}</Badge> }, { key: 'actions', label: 'Actions', render: row => <div className="row-actions"><Button size="small" variant="secondary" onClick={() => setEditing(row)}>Edit</Button><Button size="small" variant="ghost" onClick={() => setDeleting(row)} aria-label={`Delete ${row.title}`}><Trash2 size={16}/></Button></div> }]
  const remove = async () => { if (!deleting) return; await adminApi.deleteTip(deleting.id); onChange(rows.filter(item => item.id !== deleting.id)); setDeleting(null) }
  return <div className="page"><PageHeader title="Wellness tips" description="Short, reviewed guidance available to students and the assistant." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add tip</Button>}/><div className="filter-bar"><SearchBar value={query} onChange={setQuery} placeholder="Search wellness tips"/></div><DataTable rows={filtered} columns={columns} rowKey={row => row.id}/>{editing && <TipForm item={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSave={item => { onChange(editing === 'new' ? [...rows, item] : rows.map(row => row.id === item.id ? item : row)); setEditing(null) }}/>} {deleting && <ConfirmDelete name={deleting.title} onClose={() => setDeleting(null)} onConfirm={remove}/>}</div>
}
function TipForm({ item, onClose, onSave }: { item?: WellnessTip; onClose: () => void; onSave: (item: WellnessTip) => void }) {
  const [form, setForm] = useState({ title: item?.title ?? '', category: item?.category ?? '', body: item?.body ?? '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onSave(item ? await adminApi.updateTip(item.id, form) : await adminApi.addTip(form)) } catch (failure) { setError(apiError(failure)) } finally { setBusy(false) } }
  return <Modal title={item ? 'Edit wellness tip' : 'Add wellness tip'} onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="inline-alert" role="alert">{error}</div>}<FormField label="Title" htmlFor="tip-title" required><input id="tip-title" required minLength={2} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/></FormField><FormField label="Category" htmlFor="tip-category" required><input id="tip-category" required minLength={2} value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}/></FormField><FormField label="Guidance" htmlFor="tip-body" required><textarea id="tip-body" rows={5} required minLength={5} value={form.body} onChange={event => setForm({ ...form, body: event.target.value })}/></FormField><div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save tip'}</Button></div></form></Modal>
}

function ExerciseManager({ rows, onChange }: { rows: BreathingExercise[]; onChange: (rows: BreathingExercise[]) => void }) {
  const [editing, setEditing] = useState<BreathingExercise | 'new' | null>(null); const [deleting, setDeleting] = useState<BreathingExercise | null>(null)
  const columns: Column<BreathingExercise>[] = [{ key: 'name', label: 'Exercise', render: row => <strong>{row.name}</strong> }, { key: 'pattern', label: 'Pattern', render: row => `${row.inhale}-${row.hold}-${row.exhale}-${row.pause}` }, { key: 'cycles', label: 'Cycles', render: row => row.cycles }, { key: 'status', label: 'Status', render: row => <Badge tone={row.active ? 'success' : 'neutral'}>{row.active ? 'Active' : 'Hidden'}</Badge> }, { key: 'actions', label: 'Actions', render: row => <div className="row-actions"><Button size="small" variant="secondary" onClick={() => setEditing(row)}>Edit</Button><Button size="small" variant="ghost" onClick={() => setDeleting(row)} aria-label={`Delete ${row.name}`}><Trash2 size={16}/></Button></div> }]
  const remove = async () => { if (!deleting) return; await adminApi.deleteExercise(deleting.id); onChange(rows.filter(item => item.id !== deleting.id)); setDeleting(null) }
  return <div className="page"><PageHeader title="Breathing exercises" description="Patterns shown on the student breathing page." action={<Button onClick={() => setEditing('new')}><Plus size={17}/> Add exercise</Button>}/><DataTable rows={rows} columns={columns} rowKey={row => row.id}/>{editing && <ExerciseForm item={editing === 'new' ? undefined : editing} onClose={() => setEditing(null)} onSave={item => { onChange(editing === 'new' ? [...rows, item] : rows.map(row => row.id === item.id ? item : row)); setEditing(null) }}/>} {deleting && <ConfirmDelete name={deleting.name} onClose={() => setDeleting(null)} onConfirm={remove}/>}</div>
}
function ExerciseForm({ item, onClose, onSave }: { item?: BreathingExercise; onClose: () => void; onSave: (item: BreathingExercise) => void }) {
  const [form, setForm] = useState({ name: item?.name ?? '', inhale: item?.inhale ?? 4, hold: item?.hold ?? 0, exhale: item?.exhale ?? 6, pause: item?.pause ?? 0, cycles: item?.cycles ?? 5, active: item?.active ?? true }); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const number = (key: 'inhale' | 'hold' | 'exhale' | 'pause' | 'cycles', value: string) => setForm({ ...form, [key]: Number(value) })
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { onSave(item ? await adminApi.updateExercise(item.id, form) : await adminApi.addExercise(form)) } catch (failure) { setError(apiError(failure)) } finally { setBusy(false) } }
  return <Modal title={item ? 'Edit breathing exercise' : 'Add breathing exercise'} onClose={onClose}><form className="form-stack" onSubmit={submit}>{error && <div className="inline-alert" role="alert">{error}</div>}<FormField label="Name" htmlFor="exercise-name" required><input id="exercise-name" required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })}/></FormField><div className="form-grid four">{(['inhale','hold','exhale','pause'] as const).map(key => <FormField key={key} label={`${key[0].toUpperCase()}${key.slice(1)} seconds`} htmlFor={`exercise-${key}`}><input id={`exercise-${key}`} type="number" min={key === 'inhale' || key === 'exhale' ? 1 : 0} max={20} value={form[key]} onChange={event => number(key, event.target.value)}/></FormField>)}</div><FormField label="Cycles" htmlFor="exercise-cycles"><input id="exercise-cycles" type="number" min={1} max={20} value={form.cycles} onChange={event => number('cycles', event.target.value)}/></FormField><label className="checkbox-field"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })}/><span><strong>Visible to students</strong></span></label><div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save exercise'}</Button></div></form></Modal>
}

function MoodTable({ rows }: { rows: AdminMood[] }) { const columns: Column<AdminMood>[] = [{ key: 'student', label: 'Student', render: row => row.studentName }, { key: 'mood', label: 'Mood', render: row => `${row.label} · ${row.score}/5` }, { key: 'created', label: 'Created', render: row => new Date(row.createdAt).toLocaleString() }]; return <div className="page"><PageHeader title="Mood data" description="Recent student check-ins. Use aggregate patterns carefully; a mood score is not a clinical assessment."/><DataTable rows={rows} columns={columns} rowKey={row => row.id} emptyTitle="No mood data" emptyDescription="No students have saved a mood check-in."/></div> }
function UserTable({ rows }: { rows: AdminUser[] }) { const columns: Column<AdminUser>[] = [{ key: 'name', label: 'Name', render: row => <strong>{row.name}</strong> }, { key: 'email', label: 'Email', render: row => row.email }, { key: 'role', label: 'Role', render: row => <Badge tone={row.role === 'ADMIN' ? 'info' : 'neutral'}>{row.role === 'ADMIN' ? 'Administrator' : 'Student'}</Badge> }]; return <div className="page"><PageHeader title="Users" description="Accounts in the current development store."/><DataTable rows={rows} columns={columns} rowKey={row => row.id}/></div> }
function SettingsPage({ settings }: { settings: AdminSettings }) { return <div className="page"><PageHeader title="Settings" description="Read-only runtime information. Change server configuration through environment variables."/><section className="panel settings-panel"><Brain size={22}/><dl className="settings-list"><div><dt>Assistant provider</dt><dd>{settings.aiProvider}</dd></div><div><dt>Model</dt><dd>{settings.model}</dd></div><div><dt>Data store</dt><dd>{settings.storage}</dd></div><div><dt>Allowed app origin</dt><dd>{settings.campusOrigin}</dd></div></dl><p className="section-note">This development store resets when the API restarts. Configure PostgreSQL before institutional deployment.</p></section></div> }

function ConfirmDelete({ name, onClose, onConfirm }: { name: string; onClose: () => void; onConfirm: () => Promise<void> }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const confirm = async () => { setBusy(true); try { await onConfirm() } catch (failure) { setError(apiError(failure)); setBusy(false) } }; return <Modal title={`Delete ${name}?`} description="This action cannot be undone." onClose={onClose}>{error && <div className="inline-alert" role="alert">{error}</div>}<div className="form-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant="danger" disabled={busy} onClick={confirm}>{busy ? 'Deleting…' : 'Delete'}</Button></div></Modal> }
